repos:
    - repo: local
      hooks:
        - id: isort
          name: isort
          entry: pipenv run isort
          args: [--quiet]
          language: system
          types: [python]
        - id: black
          name: black
          entry: pipenv run black src
          args: [--quiet]
          language: system
          types: [python]
        - id: mypy
          name: mypy
          entry: pipenv run mypy
          args: [ "--follow-imports=skip" ]
          language: system
          types: [ python ]
        - id: flake8
          name: flake8
          entry: pipenv run flake8
          language: system
          types: [ python ]
